# Generated by Django 4.1.7 on 2023-02-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='isSold',
            new_name='is_sold',
        ),
    ]
